import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import './globals.css'
import Provider from '@/components/Provider'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Head from 'next/head'

const quickSand = Quicksand({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Natnael Demelash',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Head>
        <link rel='icon' href='./favicon.png' />
      </Head>
      <html lang='en' suppressHydrationWarning>
        <body className={quickSand.className}>
          <Provider>
            <Header />
            <main className='grow'>{children}</main>
            <Footer />
          </Provider>
        </body>
      </html>
    </>
  )
}
