import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'

import { cn } from '@/lib/utils'

import './globals.css'
import Provider from '@/components/Provider'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const quickSand = Quicksand({ subsets: ['latin'] })
// const playfair = Playfair_Display({
//   subsets: ['latin'],
//   variable: '--font-serif'
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={quickSand.className}>
        <Provider>
          <Header />
          <main className='grow'>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
